<?php

namespace Database\Seeders;

use App\Models\Module;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ModuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Module::create([
            "Id_module" => "AG_INFO_TS_EGTS101",
            "code_module" => "EGTS101",
            "annee" => 1,
            "Intitule_module" => "Arabe",
            "MHP_S1" => 15,
            "MHSYN_S1" => 5,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 20,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Arabe",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_EGTS102",
            "code_module" => "EGTS102",
            "annee" => 1,
            "Intitule_module" => "Français",
            "MHP_S1" => 25,
            "MHSYN_S1" => 10,
            "MHP_S2" => 20,
            "MHSYN_S2" => 10,
            "MHT" => 65,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Français",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_EGTS103",
            "code_module" => "EGTS103",
            "annee" => 1,
            "Intitule_module" => "Anglais technique",
            "MHP_S1" => 15,
            "MHSYN_S1" => 5,
            "MHP_S2" => 15,
            "MHSYN_S2" => 5,
            "MHT" => 40,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Anglais",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_EGTS105",
            "code_module" => "EGTS105",
            "annee" => 1,
            "Intitule_module" => "Compétences comportementales",
            "MHP_S1" => 15,
            "MHSYN_S1" => 0,
            "MHP_S2" => 15,
            "MHSYN_S2" => 0,
            "MHT" => 30,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Soft skills",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_EGTS108",
            "code_module" => "EGTS108",
            "annee" => 1,
            "Intitule_module" => "Entrepreneuriat-PIE 1",
            "MHP_S1" => 40,
            "MHSYN_S1" => 0,
            "MHP_S2" => 32,
            "MHSYN_S2" => 0,
            "MHT" => 72,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Synthèse",
            "Metier_Formateur" => "Formateur PIE",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_EGTSA106",
            "code_module" => "EGTSA106",
            "annee" => 1,
            "Intitule_module" => "Culture et techniques avancées du numérique",
            "MHP_S1" => 25,
            "MHSYN_S1" => 15,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 40,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Développement /Infrastructure Digitale /Design Digital/ Web Marketing/ Bureautique avancée",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_M101",
            "code_module" => "M101",
            "annee" => 1,
            "Intitule_module" => "Métier et formation en imprimerie",
            "MHP_S1" => 15,
            "MHSYN_S1" => 0,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 15,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Infographie ",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_M102",
            "code_module" => "M102",
            "annee" => 1,
            "Intitule_module" => "Santé et sécurité en imprimerie",
            "MHP_S1" => 20,
            "MHSYN_S1" => 10,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 30,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Infographie ",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_M103",
            "code_module" => "M103",
            "annee" => 1,
            "Intitule_module" => "Organisation d'entreprise",
            "MHP_S1" => 40,
            "MHSYN_S1" => 10,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 50,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "gestion comptabilité/marketing commerce",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_M104",
            "code_module" => "M104",
            "annee" => 1,
            "Intitule_module" => "Design graphique",
            "MHP_S1" => 75,
            "MHSYN_S1" => 15,
            "MHP_S2" => 60,
            "MHSYN_S2" => 10,
            "MHT" => 160,
            "Coef" => 4,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Infographie ",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_M105",
            "code_module" => "M105",
            "annee" => 1,
            "Intitule_module" => "Traitement des illustrations",
            "MHP_S1" => 75,
            "MHSYN_S1" => 15,
            "MHP_S2" => 60,
            "MHSYN_S2" => 10,
            "MHT" => 160,
            "Coef" => 4,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Pratique",
            "Metier_Formateur" => "Infographie ",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_M106",
            "code_module" => "M106",
            "annee" => 1,
            "Intitule_module" => "Numérisation et préparation des images",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 55,
            "MHSYN_S2" => 15,
            "MHT" => 70,
            "Coef" => 4,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Infographie ",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_M107",
            "code_module" => "M107",
            "annee" => 1,
            "Intitule_module" => "Procédés et contraintes d'impression et de finition",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 55,
            "MHSYN_S2" => 10,
            "MHT" => 65,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Impression/Finition ",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_M108",
            "code_module" => "M108",
            "annee" => 1,
            "Intitule_module" => "Assurance et Contrôle de qualité",
            "MHP_S1" => 40,
            "MHSYN_S1" => 10,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 50,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "gestion comptabilité/marketing commerce",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_M109",
            "code_module" => "M109",
            "annee" => 1,
            "Intitule_module" => "Initiation en milieu de travail",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 100,
            "Coef" => 3,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "Stage en entreprise",
            "Module_stage" => 1,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_EGTS202",
            "code_module" => "EGTS202",
            "annee" => 2,
            "Intitule_module" => "Français",
            "MHP_S1" => 25,
            "MHSYN_S1" => 10,
            "MHP_S2" => 20,
            "MHSYN_S2" => 10,
            "MHT" => 65,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Plateforme",
            "Metier_Formateur" => "Français",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_EGTS203",
            "code_module" => "EGTS203",
            "annee" => 2,
            "Intitule_module" => "Anglais technique",
            "MHP_S1" => 15,
            "MHSYN_S1" => 5,
            "MHP_S2" => 15,
            "MHSYN_S2" => 5,
            "MHT" => 40,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Plateforme",
            "Metier_Formateur" => "Anglais",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_EGTS205",
            "code_module" => "EGTS205",
            "annee" => 2,
            "Intitule_module" => "Compétences comportementales",
            "MHP_S1" => 15,
            "MHSYN_S1" => 0,
            "MHP_S2" => 15,
            "MHSYN_S2" => 0,
            "MHT" => 30,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Soft skills",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_EGTSA206",
            "code_module" => "EGTSA206",
            "annee" => 2,
            "Intitule_module" => "Culture et techniques avancées du numérique",
            "MHP_S1" => 25,
            "MHSYN_S1" => 5,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 30,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Développement /Infrastructure Digitale /Design Digital/ Web Marketing/ Bureautique avancée",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_M201",
            "code_module" => "M201",
            "annee" => 2,
            "Intitule_module" => "Traitement des images",
            "MHP_S1" => 60,
            "MHSYN_S1" => 10,
            "MHP_S2" => 60,
            "MHSYN_S2" => 10,
            "MHT" => 140,
            "Coef" => 4,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Pratique",
            "Metier_Formateur" => "Infographie ",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_M202",
            "code_module" => "M202",
            "annee" => 2,
            "Intitule_module" => "Mise en page",
            "MHP_S1" => 60,
            "MHSYN_S1" => 10,
            "MHP_S2" => 60,
            "MHSYN_S2" => 10,
            "MHT" => 140,
            "Coef" => 4,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Pratique",
            "Metier_Formateur" => "Infographie ",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_M203",
            "code_module" => "M203",
            "annee" => 2,
            "Intitule_module" => "Gestion de la couleur",
            "MHP_S1" => 35,
            "MHSYN_S1" => 10,
            "MHP_S2" => 60,
            "MHSYN_S2" => 15,
            "MHT" => 120,
            "Coef" => 3,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "Infographie ",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_M204",
            "code_module" => "M204",
            "annee" => 2,
            "Intitule_module" => "Imposition numérique",
            "MHP_S1" => 60,
            "MHSYN_S1" => 15,
            "MHP_S2" => 60,
            "MHSYN_S2" => 15,
            "MHT" => 150,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Infographie ",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_M205",
            "code_module" => "M205",
            "annee" => 2,
            "Intitule_module" => "Production des formes imprimantes",
            "MHP_S1" => 60,
            "MHSYN_S1" => 15,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 75,
            "Coef" => 3,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "Infographie ",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_M206",
            "code_module" => "M206",
            "annee" => 2,
            "Intitule_module" => "Création de site Web",
            "MHP_S1" => 50,
            "MHSYN_S1" => 10,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 60,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement /réseau Infrastructure /Design Digital/ Web Marketing",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_M207",
            "code_module" => "M207",
            "annee" => 2,
            "Intitule_module" => "Projet de fin de formation",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 35,
            "MHSYN_S2" => 10,
            "MHT" => 45,
            "Coef" => 3,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "Infographie ",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "AG_INFO_TS_M208",
            "code_module" => "M208",
            "annee" => 2,
            "Intitule_module" => "Intégration en milieu de travail",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 100,
            "Coef" => 3,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "Stage en entreprise",
            "Module_stage" => 1,
        ]);
        Module::create([
            "Id_module" => "DIA_DEV_TS_EGTS101",
            "code_module" => "EGTS101",
            "annee" => 1,
            "Intitule_module" => "Arabe",
            "MHP_S1" => 15,
            "MHSYN_S1" => 5,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 20,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Arabe",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEV_TS_EGTS102",
            "code_module" => "EGTS102",
            "annee" => 1,
            "Intitule_module" => "Français",
            "MHP_S1" => 25,
            "MHSYN_S1" => 10,
            "MHP_S2" => 20,
            "MHSYN_S2" => 10,
            "MHT" => 65,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Français",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEV_TS_EGTS103",
            "code_module" => "EGTS103",
            "annee" => 1,
            "Intitule_module" => "Anglais technique",
            "MHP_S1" => 15,
            "MHSYN_S1" => 5,
            "MHP_S2" => 15,
            "MHSYN_S2" => 5,
            "MHT" => 40,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Anglais",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEV_TS_EGTS105",
            "code_module" => "EGTS105",
            "annee" => 1,
            "Intitule_module" => "Compétences comportementales",
            "MHP_S1" => 15,
            "MHSYN_S1" => 0,
            "MHP_S2" => 15,
            "MHSYN_S2" => 0,
            "MHT" => 30,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Soft skills",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEV_TS_EGTS108",
            "code_module" => "EGTS108",
            "annee" => 1,
            "Intitule_module" => "Entrepreneuriat-PIE 1",
            "MHP_S1" => 40,
            "MHSYN_S1" => 0,
            "MHP_S2" => 32,
            "MHSYN_S2" => 0,
            "MHT" => 72,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Synthèse",
            "Metier_Formateur" => "Formateur PIE",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEV_TS_EGTSA106",
            "code_module" => "EGTSA106",
            "annee" => 1,
            "Intitule_module" => "Culture et techniques avancées du numérique",
            "MHP_S1" => 25,
            "MHSYN_S1" => 15,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 40,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Développement /Infrastructure Digitale /Design Digital/ Web Marketing/ Bureautique avancée",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEV_TS_M101",
            "code_module" => "M101",
            "annee" => 1,
            "Intitule_module" => "Métier et formation en développement digital",
            "MHP_S1" => 15,
            "MHSYN_S1" => 0,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 15,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Développement digital",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEV_TS_M102",
            "code_module" => "M102",
            "annee" => 1,
            "Intitule_module" => "Les bases de l'algorithmique",
            "MHP_S1" => 90,
            "MHSYN_S1" => 20,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 110,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement digital",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEV_TS_M103",
            "code_module" => "M103",
            "annee" => 1,
            "Intitule_module" => "Programmation Orienté Objet",
            "MHP_S1" => 90,
            "MHSYN_S1" => 20,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 110,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement digital",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEV_TS_M104",
            "code_module" => "M104",
            "annee" => 1,
            "Intitule_module" => "Sites Web statiques",
            "MHP_S1" => 85,
            "MHSYN_S1" => 20,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 105,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement digital",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEV_TS_M105",
            "code_module" => "M105",
            "annee" => 1,
            "Intitule_module" => "Programmation JavaScript",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 85,
            "MHSYN_S2" => 20,
            "MHT" => 105,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement /réseau Infrastructure",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEV_TS_M106",
            "code_module" => "M106",
            "annee" => 1,
            "Intitule_module" => "Manipulation des bases de données",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 75,
            "MHSYN_S2" => 20,
            "MHT" => 95,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement /réseau Infrastructure /Design Digital/ Web Marketing",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEV_TS_M107",
            "code_module" => "M107",
            "annee" => 1,
            "Intitule_module" => "Sites Web dynamiques",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 90,
            "MHSYN_S2" => 20,
            "MHT" => 110,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement digital",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEV_TS_M108",
            "code_module" => "M108",
            "annee" => 1,
            "Intitule_module" => "Sécurité des systèmes d'information",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 35,
            "MHSYN_S2" => 5,
            "MHT" => 40,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement digital",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOAM_TS_EGTS202",
            "code_module" => "EGTS202",
            "annee" => 2,
            "Intitule_module" => "Français",
            "MHP_S1" => 25,
            "MHSYN_S1" => 10,
            "MHP_S2" => 20,
            "MHSYN_S2" => 10,
            "MHT" => 65,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Plateforme",
            "Metier_Formateur" => "Français",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOAM_TS_EGTS203",
            "code_module" => "EGTS203",
            "annee" => 2,
            "Intitule_module" => "Anglais technique",
            "MHP_S1" => 15,
            "MHSYN_S1" => 5,
            "MHP_S2" => 15,
            "MHSYN_S2" => 5,
            "MHT" => 40,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Plateforme",
            "Metier_Formateur" => "Anglais",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOAM_TS_EGTS205",
            "code_module" => "EGTS205",
            "annee" => 2,
            "Intitule_module" => "Compétences comportementales",
            "MHP_S1" => 15,
            "MHSYN_S1" => 0,
            "MHP_S2" => 15,
            "MHSYN_S2" => 0,
            "MHT" => 30,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Soft skills",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOAM_TS_EGTSA206",
            "code_module" => "EGTSA206",
            "annee" => 2,
            "Intitule_module" => "Culture et techniques avancées du numérique",
            "MHP_S1" => 25,
            "MHSYN_S1" => 5,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 30,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Développement /Infrastructure Digitale /Design Digital/ Web Marketing/ Bureautique avancée",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOAM_TS_M201",
            "code_module" => "M201",
            "annee" => 2,
            "Intitule_module" => "Bases du développement Android",
            "MHP_S1" => 80,
            "MHSYN_S1" => 25,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 105,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement Mobile",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOAM_TS_M202",
            "code_module" => "M202",
            "annee" => 2,
            "Intitule_module" => "Programmation KOTLIN",
            "MHP_S1" => 65,
            "MHSYN_S1" => 15,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 80,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement Mobile",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOAM_TS_M203",
            "code_module" => "M203",
            "annee" => 2,
            "Intitule_module" => "Gestion de projet",
            "MHP_S1" => 20,
            "MHSYN_S1" => 7.5,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 27.5,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement informatique",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOAM_TS_M204",
            "code_module" => "M204",
            "annee" => 2,
            "Intitule_module" => "Initiation aux composants et modèle d’une application Android ",
            "MHP_S1" => 65,
            "MHSYN_S1" => 15,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 80,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement Mobile",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOAM_TS_M205",
            "code_module" => "M205",
            "annee" => 2,
            "Intitule_module" => "Développement des interfaces utilisateurs sous Android ",
            "MHP_S1" => 60,
            "MHSYN_S1" => 10,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 70,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement Mobile",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOAM_TS_M206",
            "code_module" => "M206",
            "annee" => 2,
            "Intitule_module" => "Elaboration d'une application Android sécurisée ",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 65,
            "MHSYN_S2" => 15,
            "MHT" => 80,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement Mobile",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOAM_TS_M207",
            "code_module" => "M207",
            "annee" => 2,
            "Intitule_module" => "Développement des applications IOS ",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 65,
            "MHSYN_S2" => 15,
            "MHT" => 80,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement Mobile",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOAM_TS_M208",
            "code_module" => "M208",
            "annee" => 2,
            "Intitule_module" => "Développement multiplateforme ",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 65,
            "MHSYN_S2" => 15,
            "MHT" => 80,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement Mobile",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOAM_TS_M209",
            "code_module" => "M209",
            "annee" => 2,
            "Intitule_module" => "Intégration du milieu professionnel",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 160,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "",
            "Module_stage" => 1,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOWFS_TS_EGTS202",
            "code_module" => "EGTS202",
            "annee" => 2,
            "Intitule_module" => "Français",
            "MHP_S1" => 25,
            "MHSYN_S1" => 10,
            "MHP_S2" => 20,
            "MHSYN_S2" => 10,
            "MHT" => 65,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Plateforme",
            "Metier_Formateur" => "Français",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOWFS_TS_EGTS203",
            "code_module" => "EGTS203",
            "annee" => 2,
            "Intitule_module" => "Anglais technique",
            "MHP_S1" => 15,
            "MHSYN_S1" => 5,
            "MHP_S2" => 15,
            "MHSYN_S2" => 5,
            "MHT" => 40,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Plateforme",
            "Metier_Formateur" => "Anglais",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOWFS_TS_EGTS205",
            "code_module" => "EGTS205",
            "annee" => 2,
            "Intitule_module" => "Compétences comportementales",
            "MHP_S1" => 15,
            "MHSYN_S1" => 0,
            "MHP_S2" => 15,
            "MHSYN_S2" => 0,
            "MHT" => 30,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Soft skills",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOWFS_TS_EGTSA206",
            "code_module" => "EGTSA206",
            "annee" => 2,
            "Intitule_module" => "Culture et techniques avancées du numérique",
            "MHP_S1" => 25,
            "MHSYN_S1" => 5,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 30,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Développement /Infrastructure Digitale /Design Digital/ Web Marketing/ Bureautique avancée",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOWFS_TS_M201",
            "code_module" => "M201",
            "annee" => 2,
            "Intitule_module" => "Préparation d'un projet web",
            "MHP_S1" => 45,
            "MHSYN_S1" => 15,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 60,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement digital",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOWFS_TS_M202",
            "code_module" => "M202",
            "annee" => 2,
            "Intitule_module" => "Approche agile",
            "MHP_S1" => 75,
            "MHSYN_S1" => 25,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 100,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement digital",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOWFS_TS_M203",
            "code_module" => "M203",
            "annee" => 2,
            "Intitule_module" => "Gestion des données",
            "MHP_S1" => 75,
            "MHSYN_S1" => 25,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 100,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement digital",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOWFS_TS_M204",
            "code_module" => "M204",
            "annee" => 2,
            "Intitule_module" => "Développement front-end",
            "MHP_S1" => 75,
            "MHSYN_S1" => 25,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 100,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement digital",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOWFS_TS_M205",
            "code_module" => "M205",
            "annee" => 2,
            "Intitule_module" => "Développement back-end",
            "MHP_S1" => 20,
            "MHSYN_S1" => 5,
            "MHP_S2" => 80,
            "MHSYN_S2" => 15,
            "MHT" => 120,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement digital",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOWFS_TS_M206",
            "code_module" => "M206",
            "annee" => 2,
            "Intitule_module" => "Création d'une application Cloud native",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 65,
            "MHSYN_S2" => 25,
            "MHT" => 90,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement digital",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOWFS_TS_M207",
            "code_module" => "M207",
            "annee" => 2,
            "Intitule_module" => "Projet de synthèse",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 45,
            "MHSYN_S2" => 15,
            "MHT" => 60,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement digital",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOWFS_TS_M208",
            "code_module" => "M208",
            "annee" => 2,
            "Intitule_module" => "Intégration du milieu professionnel",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 160,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "",
            "Module_stage" => 1,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOWFS_TS_RCDS_EGTS101",
            "code_module" => "EGTS101",
            "annee" => 1,
            "Intitule_module" => "Arabe",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 7.5,
            "MHSYN_S2" => 0,
            "MHT" => 7.5,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Arabe",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOWFS_TS_RCDS_EGTS102",
            "code_module" => "EGTS102",
            "annee" => 1,
            "Intitule_module" => "Français",
            "MHP_S1" => 10,
            "MHSYN_S1" => 0,
            "MHP_S2" => 10,
            "MHSYN_S2" => 0,
            "MHT" => 20,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Français",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOWFS_TS_RCDS_EGTS103",
            "code_module" => "EGTS103",
            "annee" => 1,
            "Intitule_module" => "Anglais technique",
            "MHP_S1" => 10,
            "MHSYN_S1" => 0,
            "MHP_S2" => 10,
            "MHSYN_S2" => 0,
            "MHT" => 20,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Anglais",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOWFS_TS_RCDS_EGTS105",
            "code_module" => "EGTS105",
            "annee" => 1,
            "Intitule_module" => "Compétences comportementales",
            "MHP_S1" => 10,
            "MHSYN_S1" => 0,
            "MHP_S2" => 10,
            "MHSYN_S2" => 0,
            "MHT" => 20,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Soft skills",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOWFS_TS_RCDS_EGTSA106",
            "code_module" => "EGTSA106",
            "annee" => 1,
            "Intitule_module" => "Culture et techniques avancées du numérique",
            "MHP_S1" => 7.5,
            "MHSYN_S1" => 0,
            "MHP_S2" => 7.5,
            "MHSYN_S2" => 0,
            "MHT" => 15,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Développement /Infrastructure Digitale /Design Digital/ Web Marketing/ Bureautique avancée",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOWFS_TS_RCDS_M101",
            "code_module" => "M101",
            "annee" => 1,
            "Intitule_module" => "Métier et formation en développement digital",
            "MHP_S1" => 5,
            "MHSYN_S1" => 0,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 5,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement informatique",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOWFS_TS_RCDS_M102",
            "code_module" => "M102",
            "annee" => 1,
            "Intitule_module" => "Les bases de l'algorithmique",
            "MHP_S1" => 50,
            "MHSYN_S1" => 0,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 50,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement informatique",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOWFS_TS_RCDS_M103",
            "code_module" => "M103",
            "annee" => 1,
            "Intitule_module" => "Programmation Orienté Objet",
            "MHP_S1" => 50,
            "MHSYN_S1" => 0,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 50,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement informatique",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOWFS_TS_RCDS_M104",
            "code_module" => "M104",
            "annee" => 1,
            "Intitule_module" => "Sites Web statiques",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 45,
            "MHSYN_S2" => 0,
            "MHT" => 45,
            "Coef" => 3,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement Web et multimédia",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_DEVOWFS_TS_RCDS_M105",
            "code_module" => "M105",
            "annee" => 1,
            "Intitule_module" => "Programmation JavaScript",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 45,
            "MHSYN_S2" => 0,
            "MHT" => 45,
            "Coef" => 3,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement Web et multimédia",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_ID_TS_EGTS101",
            "code_module" => "EGTS101",
            "annee" => 1,
            "Intitule_module" => "Arabe",
            "MHP_S1" => 15,
            "MHSYN_S1" => 5,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 20,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Arabe",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_ID_TS_EGTS102",
            "code_module" => "EGTS102",
            "annee" => 1,
            "Intitule_module" => "Français",
            "MHP_S1" => 25,
            "MHSYN_S1" => 10,
            "MHP_S2" => 20,
            "MHSYN_S2" => 10,
            "MHT" => 65,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Français",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_ID_TS_EGTS103",
            "code_module" => "EGTS103",
            "annee" => 1,
            "Intitule_module" => "Anglais technique",
            "MHP_S1" => 15,
            "MHSYN_S1" => 5,
            "MHP_S2" => 15,
            "MHSYN_S2" => 5,
            "MHT" => 40,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Anglais",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_ID_TS_EGTS105",
            "code_module" => "EGTS105",
            "annee" => 1,
            "Intitule_module" => "Compétences comportementales",
            "MHP_S1" => 15,
            "MHSYN_S1" => 0,
            "MHP_S2" => 15,
            "MHSYN_S2" => 0,
            "MHT" => 30,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Soft skills",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_ID_TS_EGTS108",
            "code_module" => "EGTS108",
            "annee" => 1,
            "Intitule_module" => "Entrepreneuriat-PIE 1",
            "MHP_S1" => 40,
            "MHSYN_S1" => 0,
            "MHP_S2" => 32,
            "MHSYN_S2" => 0,
            "MHT" => 72,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Synthèse",
            "Metier_Formateur" => "Formateur PIE",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_ID_TS_EGTSA106",
            "code_module" => "EGTSA106",
            "annee" => 1,
            "Intitule_module" => "Culture et techniques avancées du numérique",
            "MHP_S1" => 25,
            "MHSYN_S1" => 15,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 40,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Développement /Infrastructure Digitale /Design Digital/ Web Marketing/ Bureautique avancée",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_ID_TS_M101",
            "code_module" => "M101",
            "annee" => 1,
            "Intitule_module" => "Métier et formation en infrastructure digital",
            "MHP_S1" => 15,
            "MHSYN_S1" => 0,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 15,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Réseaux / Systèmes Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_ID_TS_M102",
            "code_module" => "M102",
            "annee" => 1,
            "Intitule_module" => "Les enjeux d'un système d'information ",
            "MHP_S1" => 40,
            "MHSYN_S1" => 7.5,
            "MHP_S2" => 15,
            "MHSYN_S2" => 5,
            "MHT" => 67.5,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Réseaux / Systèmes Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_ID_TS_M103",
            "code_module" => "M103",
            "annee" => 1,
            "Intitule_module" => "Conception d'un réseau informatique ",
            "MHP_S1" => 90,
            "MHSYN_S1" => 22.5,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 112.5,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Réseaux / Systèmes Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_ID_TS_M104",
            "code_module" => "M104",
            "annee" => 1,
            "Intitule_module" => "Fonctionnement du système d'exploitation ",
            "MHP_S1" => 95,
            "MHSYN_S1" => 27.5,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 122.5,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_ID_TS_M105",
            "code_module" => "M105",
            "annee" => 1,
            "Intitule_module" => "Gestion de l'infrastructure virtualisée ",
            "MHP_S1" => 20,
            "MHSYN_S1" => 7.5,
            "MHP_S2" => 65,
            "MHSYN_S2" => 17.5,
            "MHT" => 110,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_ID_TS_M106",
            "code_module" => "M106",
            "annee" => 1,
            "Intitule_module" => "Automatisation des tâches d'administration",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 85,
            "MHSYN_S2" => 25,
            "MHT" => 110,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Réseaux / Systèmes Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_ID_TS_M107",
            "code_module" => "M107",
            "annee" => 1,
            "Intitule_module" => "Sécurité des systèmes d'information",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 55,
            "MHSYN_S2" => 12.5,
            "MHT" => 67.5,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Réseaux / Systèmes Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_ID_TS_M108",
            "code_module" => "M108",
            "annee" => 1,
            "Intitule_module" => "Processus et outils de veille technologique",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 35,
            "MHSYN_S2" => 7.5,
            "MHT" => 42.5,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Réseaux / Systèmes Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCC_TS_EGTS202",
            "code_module" => "EGTS202",
            "annee" => 2,
            "Intitule_module" => "Français",
            "MHP_S1" => 25,
            "MHSYN_S1" => 10,
            "MHP_S2" => 20,
            "MHSYN_S2" => 10,
            "MHT" => 65,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Plateforme",
            "Metier_Formateur" => "Français",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCC_TS_EGTS203",
            "code_module" => "EGTS203",
            "annee" => 2,
            "Intitule_module" => "Anglais technique",
            "MHP_S1" => 15,
            "MHSYN_S1" => 5,
            "MHP_S2" => 15,
            "MHSYN_S2" => 5,
            "MHT" => 40,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Plateforme",
            "Metier_Formateur" => "Anglais",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCC_TS_EGTS205",
            "code_module" => "EGTS205",
            "annee" => 2,
            "Intitule_module" => "Compétences comportementales",
            "MHP_S1" => 15,
            "MHSYN_S1" => 0,
            "MHP_S2" => 15,
            "MHSYN_S2" => 0,
            "MHT" => 30,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Soft skills",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCC_TS_EGTSA206",
            "code_module" => "EGTSA206",
            "annee" => 2,
            "Intitule_module" => "Culture et techniques avancées du numérique",
            "MHP_S1" => 25,
            "MHSYN_S1" => 5,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 30,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Développement /Infrastructure Digitale /Design Digital/ Web Marketing/ Bureautique avancée",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCC_TS_M201",
            "code_module" => "M201",
            "annee" => 2,
            "Intitule_module" => "Architecture Cloud",
            "MHP_S1" => 35,
            "MHSYN_S1" => 5,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 40,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCC_TS_M202",
            "code_module" => "M202",
            "annee" => 2,
            "Intitule_module" => "Environnement Cloud propriétaire en ligne public",
            "MHP_S1" => 35,
            "MHSYN_S1" => 5,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 40,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCC_TS_M203",
            "code_module" => "M203",
            "annee" => 2,
            "Intitule_module" => "Implémentation d'un environnement Cloud avec une solution libre",
            "MHP_S1" => 95,
            "MHSYN_S1" => 30,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 125,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCC_TS_M204",
            "code_module" => "M204",
            "annee" => 2,
            "Intitule_module" => "Administration d'un environnement Cloud propriétaire en ligne public",
            "MHP_S1" => 20,
            "MHSYN_S1" => 7.5,
            "MHP_S2" => 60,
            "MHSYN_S2" => 10,
            "MHT" => 97.5,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCC_TS_M205",
            "code_module" => "M205",
            "annee" => 2,
            "Intitule_module" => "Sécurisation d'un environnement Cloud propriétaire en ligne public",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 80,
            "MHSYN_S2" => 20,
            "MHT" => 100,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCC_TS_M206",
            "code_module" => "M206",
            "annee" => 2,
            "Intitule_module" => "Gouvernance des données dans le Cloud",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 50,
            "MHSYN_S2" => 7.5,
            "MHT" => 57.5,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCC_TS_M207",
            "code_module" => "M207",
            "annee" => 2,
            "Intitule_module" => "Stratégie de maintien d'un SI dans un Cloud propriétaire en ligne public",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 62.5,
            "MHSYN_S2" => 17.5,
            "MHT" => 80,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCC_TS_M208",
            "code_module" => "M208",
            "annee" => 2,
            "Intitule_module" => "Intégration du milieu professionnel",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 160,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "",
            "Module_stage" => 1,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCS_TS_EGTS202",
            "code_module" => "EGTS202",
            "annee" => 2,
            "Intitule_module" => "Français",
            "MHP_S1" => 25,
            "MHSYN_S1" => 10,
            "MHP_S2" => 20,
            "MHSYN_S2" => 10,
            "MHT" => 65,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Plateforme",
            "Metier_Formateur" => "Français",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCS_TS_EGTS203",
            "code_module" => "EGTS203",
            "annee" => 2,
            "Intitule_module" => "Anglais technique",
            "MHP_S1" => 15,
            "MHSYN_S1" => 5,
            "MHP_S2" => 15,
            "MHSYN_S2" => 5,
            "MHT" => 40,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Plateforme",
            "Metier_Formateur" => "Anglais",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCS_TS_EGTS205",
            "code_module" => "EGTS205",
            "annee" => 2,
            "Intitule_module" => "Compétences comportementales",
            "MHP_S1" => 15,
            "MHSYN_S1" => 0,
            "MHP_S2" => 15,
            "MHSYN_S2" => 0,
            "MHT" => 30,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Soft skills",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCS_TS_EGTSA206",
            "code_module" => "EGTSA206",
            "annee" => 2,
            "Intitule_module" => "Culture et techniques avancées du numérique",
            "MHP_S1" => 25,
            "MHSYN_S1" => 5,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 30,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Développement /Infrastructure Digitale /Design Digital/ Web Marketing/ Bureautique avancée",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCS_TS_M201",
            "code_module" => "M201",
            "annee" => 2,
            "Intitule_module" => "Fondamentaux de la cybersécurité",
            "MHP_S1" => 55,
            "MHSYN_S1" => 15,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 70,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCS_TS_M202",
            "code_module" => "M202",
            "annee" => 2,
            "Intitule_module" => "Méthodologies des tests d’intrusions",
            "MHP_S1" => 80,
            "MHSYN_S1" => 17.5,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 97.5,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCS_TS_M203",
            "code_module" => "M203",
            "annee" => 2,
            "Intitule_module" => "Analyse des attaques et des incidents de Cybersécurité",
            "MHP_S1" => 80,
            "MHSYN_S1" => 17.5,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 97.5,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCS_TS_M204",
            "code_module" => "M204",
            "annee" => 2,
            "Intitule_module" => "Durcissement de la sécurité des systèmes et réseaux informatiques ",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 75,
            "MHSYN_S2" => 10,
            "MHT" => 85,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCS_TS_M205",
            "code_module" => "M205",
            "annee" => 2,
            "Intitule_module" => "Méthodes d'investigation numérique",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 75,
            "MHSYN_S2" => 10,
            "MHT" => 85,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCS_TS_M206",
            "code_module" => "M206",
            "annee" => 2,
            "Intitule_module" => "Stratégies de gestion des risques",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 75,
            "MHSYN_S2" => 10,
            "MHT" => 85,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOCS_TS_M207",
            "code_module" => "M207",
            "annee" => 2,
            "Intitule_module" => "Intégration du milieu professionnel",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 160,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "",
            "Module_stage" => 1,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOSR_TS_EGTS202",
            "code_module" => "EGTS202",
            "annee" => 2,
            "Intitule_module" => "Français",
            "MHP_S1" => 25,
            "MHSYN_S1" => 10,
            "MHP_S2" => 20,
            "MHSYN_S2" => 10,
            "MHT" => 65,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Plateforme",
            "Metier_Formateur" => "Français",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOSR_TS_EGTS203",
            "code_module" => "EGTS203",
            "annee" => 2,
            "Intitule_module" => "Anglais technique",
            "MHP_S1" => 15,
            "MHSYN_S1" => 5,
            "MHP_S2" => 15,
            "MHSYN_S2" => 5,
            "MHT" => 40,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Plateforme",
            "Metier_Formateur" => "Anglais",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOSR_TS_EGTS205",
            "code_module" => "EGTS205",
            "annee" => 2,
            "Intitule_module" => "Compétences comportementales",
            "MHP_S1" => 15,
            "MHSYN_S1" => 0,
            "MHP_S2" => 15,
            "MHSYN_S2" => 0,
            "MHT" => 30,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Soft skills",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOSR_TS_EGTSA206",
            "code_module" => "EGTSA206",
            "annee" => 2,
            "Intitule_module" => "Culture et techniques avancées du numérique",
            "MHP_S1" => 25,
            "MHSYN_S1" => 5,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 30,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Développement /Infrastructure Digitale /Design Digital/ Web Marketing/ Bureautique avancée",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOSR_TS_M201",
            "code_module" => "M201",
            "annee" => 2,
            "Intitule_module" => "Mise en place d’une infrastructure réseaux",
            "MHP_S1" => 95,
            "MHSYN_S1" => 25,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 120,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOSR_TS_M202",
            "code_module" => "M202",
            "annee" => 2,
            "Intitule_module" => "Administration d'un environnement Windows",
            "MHP_S1" => 85,
            "MHSYN_S1" => 20,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 105,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOSR_TS_M203",
            "code_module" => "M203",
            "annee" => 2,
            "Intitule_module" => "Administration d'un environnement Linux ",
            "MHP_S1" => 85,
            "MHSYN_S1" => 20,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 105,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOSR_TS_M204",
            "code_module" => "M204",
            "annee" => 2,
            "Intitule_module" => "Enjeux de la technologie SDN",
            "MHP_S1" => 35,
            "MHSYN_S1" => 10,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 45,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOSR_TS_M205",
            "code_module" => "M205",
            "annee" => 2,
            "Intitule_module" => "Administration d'un environnement Cloud ",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 60,
            "MHSYN_S2" => 15,
            "MHT" => 75,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOSR_TS_M206",
            "code_module" => "M206",
            "annee" => 2,
            "Intitule_module" => "Sécurité d'une infrastrcutre digitale",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 50,
            "MHSYN_S2" => 10,
            "MHT" => 60,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOSR_TS_M207",
            "code_module" => "M207",
            "annee" => 2,
            "Intitule_module" => "Gestion d'un projet d'infrastruture digitale",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 35,
            "MHSYN_S2" => 10,
            "MHT" => 45,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_IDOSR_TS_M208",
            "code_module" => "M208",
            "annee" => 2,
            "Intitule_module" => "Intégration du milieu professionnel",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 160,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "",
            "Module_stage" => 1,
        ]);
        Module::create([
            "Id_module" => "GC_PIE_FQ_M101",
            "code_module" => "M101",
            "annee" => 1,
            "Intitule_module" => "Innovation et service client",
            "MHP_S1" => 27.5,
            "MHSYN_S1" => 0,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 27.5,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Synthèse",
            "Metier_Formateur" => "Gestion/ Comptabilité",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "GC_PIE_FQ_M102",
            "code_module" => "M102",
            "annee" => 1,
            "Intitule_module" => "Business design",
            "MHP_S1" => 27.5,
            "MHSYN_S1" => 0,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 27.5,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Synthèse",
            "Metier_Formateur" => "COMMERCE / VENTE",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "GC_PIE_FQ_M103",
            "code_module" => "M103",
            "annee" => 1,
            "Intitule_module" => "Compétences business",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 25,
            "MHSYN_S2" => 0,
            "MHT" => 25,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Synthèse",
            "Metier_Formateur" => "Gestion/ Comptabilité",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_CMOSE_FQ_M101",
            "code_module" => "M101",
            "annee" => 1,
            "Intitule_module" => "Préparation à la certification Excel intermédiaire",
            "MHP_S1" => 10,
            "MHSYN_S1" => 5,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 15,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Pratique",
            "Metier_Formateur" => "Bureautique ",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_CMOSE_FQ_M102",
            "code_module" => "M102",
            "annee" => 1,
            "Intitule_module" => "Préparation à la certification Excel expert",
            "MHP_S1" => 10,
            "MHSYN_S1" => 5,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 15,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Pratique",
            "Metier_Formateur" => "Bureautique ",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_CMOSW_FQ_M101",
            "code_module" => "M101",
            "annee" => 1,
            "Intitule_module" => "Préparation à la certification Word intermédiaire",
            "MHP_S1" => 10,
            "MHSYN_S1" => 5,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 15,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Pratique",
            "Metier_Formateur" => "Bureautique ",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "DIA_CMOSW_FQ_M102",
            "code_module" => "M102",
            "annee" => 1,
            "Intitule_module" => "Préparation à la certification Word expert",
            "MHP_S1" => 10,
            "MHSYN_S1" => 5,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 15,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Pratique",
            "Metier_Formateur" => "Bureautique ",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_MIR_BP_M201",
            "code_module" => "M201",
            "annee" => 2,
            "Intitule_module" => "Bureautique",
            "MHP_S1" => 60,
            "MHSYN_S1" => 0,
            "MHP_S2" => 60,
            "MHSYN_S2" => 0,
            "MHT" => 120,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "Bureautique ",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_MIR_BP_M202",
            "code_module" => "M202",
            "annee" => 2,
            "Intitule_module" => "L'essentiel en technologie de l'information",
            "MHP_S1" => 95,
            "MHSYN_S1" => 0,
            "MHP_S2" => 95,
            "MHSYN_S2" => 0,
            "MHT" => 190,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "Développement / Réseaux & systèmes",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_MIR_BP_M203",
            "code_module" => "M203",
            "annee" => 2,
            "Intitule_module" => "SE Open Source (Linux)",
            "MHP_S1" => 50,
            "MHSYN_S1" => 0,
            "MHP_S2" => 50,
            "MHSYN_S2" => 0,
            "MHT" => 100,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_MIR_BP_M204",
            "code_module" => "M204",
            "annee" => 2,
            "Intitule_module" => "sécurité d'un poste informatique",
            "MHP_S1" => 47,
            "MHSYN_S1" => 0,
            "MHP_S2" => 47,
            "MHSYN_S2" => 0,
            "MHT" => 94,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_MIR_BP_M205",
            "code_module" => "M205",
            "annee" => 2,
            "Intitule_module" => "Diagnostic et maintenance d'un poste informatique",
            "MHP_S1" => 45,
            "MHSYN_S1" => 0,
            "MHP_S2" => 45,
            "MHSYN_S2" => 0,
            "MHT" => 90,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_MIR_BP_M301",
            "code_module" => "M301",
            "annee" => 3,
            "Intitule_module" => "Installation et configuration d'un réseau informatique",
            "MHP_S1" => 90,
            "MHSYN_S1" => 0,
            "MHP_S2" => 90,
            "MHSYN_S2" => 0,
            "MHT" => 180,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_MIR_BP_M302",
            "code_module" => "M302",
            "annee" => 3,
            "Intitule_module" => "Administration d'un réseau sous Windows",
            "MHP_S1" => 75,
            "MHSYN_S1" => 0,
            "MHP_S2" => 75,
            "MHSYN_S2" => 0,
            "MHT" => 150,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_MIR_BP_M303",
            "code_module" => "M303",
            "annee" => 3,
            "Intitule_module" => "Sécurité d'un réseau informatique",
            "MHP_S1" => 50,
            "MHSYN_S1" => 0,
            "MHP_S2" => 50,
            "MHSYN_S2" => 0,
            "MHT" => 100,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_MIR_BP_M304",
            "code_module" => "M304",
            "annee" => 3,
            "Intitule_module" => "Diagnostic, maintenance et assistance technique d'un réseau informatique",
            "MHP_S1" => 60,
            "MHSYN_S1" => 0,
            "MHP_S2" => 60,
            "MHSYN_S2" => 0,
            "MHT" => 120,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_MIR_BP_M305",
            "code_module" => "M305",
            "annee" => 3,
            "Intitule_module" => "Moyens de recherche d'emploi",
            "MHP_S1" => 13,
            "MHSYN_S1" => 0,
            "MHP_S2" => 13,
            "MHSYN_S2" => 0,
            "MHT" => 26,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "Soft skills",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_MIR_BP_M306",
            "code_module" => "M306",
            "annee" => 3,
            "Intitule_module" => "Initégration au milieu de travail",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 160,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "Systèmes & Réseaux Informatiques",
            "Module_stage" => 1,
        ]);
        Module::create([
            "Id_module" => "NTIC_TDI_TS_RCDS_EGTS202",
            "code_module" => "EGTS202",
            "annee" => 2,
            "Intitule_module" => "Français",
            "MHP_S1" => 12.5,
            "MHSYN_S1" => 0,
            "MHP_S2" => 10,
            "MHSYN_S2" => 0,
            "MHT" => 22.5,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Français",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_TDI_TS_RCDS_EGTS203",
            "code_module" => "EGTS203",
            "annee" => 2,
            "Intitule_module" => "Anglais technique",
            "MHP_S1" => 10,
            "MHSYN_S1" => 0,
            "MHP_S2" => 10,
            "MHSYN_S2" => 0,
            "MHT" => 20,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Anglais",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_TDI_TS_RCDS_EGTS204",
            "code_module" => "EGTS204",
            "annee" => 2,
            "Intitule_module" => "Culture entrepreneuriale",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 15,
            "MHSYN_S2" => 0,
            "MHT" => 15,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Synthèse",
            "Metier_Formateur" => "gestion comptabilité/marketing commerce",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_TDI_TS_RCDS_EGTS205",
            "code_module" => "EGTS205",
            "annee" => 2,
            "Intitule_module" => "Compétences comportementales",
            "MHP_S1" => 7.5,
            "MHSYN_S1" => 0,
            "MHP_S2" => 7.5,
            "MHSYN_S2" => 0,
            "MHT" => 15,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Soft skills",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_TDI_TS_RCDS_EGTSA206",
            "code_module" => "EGTSA206",
            "annee" => 2,
            "Intitule_module" => "Culture et techniques avancées du numérique",
            "MHP_S1" => 7.5,
            "MHSYN_S1" => 0,
            "MHP_S2" => 7.5,
            "MHSYN_S2" => 0,
            "MHT" => 15,
            "Coef" => 1,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique",
            "Metier_Formateur" => "Développement /Infrastructure Digitale /Design Digital/ Web Marketing/ Bureautique avancée",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_TDI_TS_RCDS_M201",
            "code_module" => "M201",
            "annee" => 2,
            "Intitule_module" => "Programmation événementielle et Orientée Objet",
            "MHP_S1" => 77.5,
            "MHSYN_S1" => 0,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 77.5,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement digital",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_TDI_TS_RCDS_M202",
            "code_module" => "M202",
            "annee" => 2,
            "Intitule_module" => "Analyse et conception orientée objet",
            "MHP_S1" => 25,
            "MHSYN_S1" => 0,
            "MHP_S2" => 20,
            "MHSYN_S2" => 0,
            "MHT" => 45,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "Développement digital",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_TDI_TS_RCDS_M203",
            "code_module" => "M203",
            "annee" => 2,
            "Intitule_module" => "Bases de données",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 70,
            "MHSYN_S2" => 0,
            "MHT" => 70,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "Développement digital",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_TDI_TS_RCDS_EGTS302",
            "code_module" => "EGTS302",
            "annee" => 3,
            "Intitule_module" => "Français ",
            "MHP_S1" => 15,
            "MHSYN_S1" => 0,
            "MHP_S2" => 15,
            "MHSYN_S2" => 0,
            "MHT" => 30,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Plateforme",
            "Metier_Formateur" => "Français",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_TDI_TS_RCDS_EGTS303",
            "code_module" => "EGTS303",
            "annee" => 3,
            "Intitule_module" => "Anglais technique",
            "MHP_S1" => 10,
            "MHSYN_S1" => 0,
            "MHP_S2" => 10,
            "MHSYN_S2" => 0,
            "MHT" => 20,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Plateforme",
            "Metier_Formateur" => "Anglais",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_TDI_TS_RCDS_EGTS304",
            "code_module" => "EGTS304",
            "annee" => 3,
            "Intitule_module" => "Culture entrepreunariale",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 20,
            "MHSYN_S2" => 0,
            "MHT" => 20,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Synthèse",
            "Metier_Formateur" => "gestion comptabilité/marketing commerce",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_TDI_TS_RCDS_EGTS305",
            "code_module" => "EGTS305",
            "annee" => 3,
            "Intitule_module" => "Compétences comportementales",
            "MHP_S1" => 10,
            "MHSYN_S1" => 0,
            "MHP_S2" => 10,
            "MHSYN_S2" => 0,
            "MHT" => 20,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Soft skills",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_TDI_TS_RCDS_M301",
            "code_module" => "M301",
            "annee" => 3,
            "Intitule_module" => "Développement d'application client/serveur",
            "MHP_S1" => 45,
            "MHSYN_S1" => 0,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 45,
            "Coef" => 3,
            "EFM_Regional" => 1,
            "Nature_Evaluation" => "Théorique/Pratique",
            "Metier_Formateur" => "Développement digital",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_TDI_TS_RCDS_M302",
            "code_module" => "M302",
            "annee" => 3,
            "Intitule_module" => "Développement web côté client",
            "MHP_S1" => 45,
            "MHSYN_S1" => 0,
            "MHP_S2" => 0,
            "MHSYN_S2" => 0,
            "MHT" => 45,
            "Coef" => 2,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "Développement digital",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_TDI_TS_RCDS_M303",
            "code_module" => "M303",
            "annee" => 3,
            "Intitule_module" => "Développement web côté serveur",
            "MHP_S1" => 15,
            "MHSYN_S1" => 0,
            "MHP_S2" => 35,
            "MHSYN_S2" => 0,
            "MHT" => 50,
            "Coef" => 3,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "Développement digital",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_TDI_TS_RCDS_M304",
            "code_module" => "M304",
            "annee" => 3,
            "Intitule_module" => "Développement d'applications mobiles",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 35,
            "MHSYN_S2" => 0,
            "MHT" => 35,
            "Coef" => 3,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "Développement digital",
            "Module_stage" => 0,
        ]);
        Module::create([
            "Id_module" => "NTIC_TDI_TS_RCDS_M305",
            "code_module" => "M305",
            "annee" => 3,
            "Intitule_module" => "Projet de fin de formation",
            "MHP_S1" => 0,
            "MHSYN_S1" => 0,
            "MHP_S2" => 15,
            "MHSYN_S2" => 0,
            "MHT" => 15,
            "Coef" => 3,
            "EFM_Regional" => 0,
            "Nature_Evaluation" => "",
            "Metier_Formateur" => "Développement digital",
            "Module_stage" => 0,
        ]);
    }
}
