<?php

namespace Database\Seeders;

use App\Models\Seance;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SeanceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        Seance::create([
            'Id_Salle' => 'SDD1',
            'Code_Groupe' => 'DEVOWFS201',
            'formateur_Matricule' => '13566',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '2S1',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD3',
            'Code_Groupe' => 'DEVOWFS205',
            'formateur_Matricule' => '17544',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '2S1',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD5',
            'Code_Groupe' => 'IDOSR204',
            'formateur_Matricule' => '15035',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '2S1',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID1',
            'Code_Groupe' => 'IDOSR201',
            'formateur_Matricule' => '10854',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '2S1',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID3',
            'Code_Groupe' => 'IDOSR203',
            'formateur_Matricule' => '13552',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '2S1',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SINFO',
            'Code_Groupe' => 'INFO202',
            'formateur_Matricule' => '8438',
            'Id_module' => 'AG_INFO_TS_M201',
            'code_seance' => '2S1',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL1',
            'Code_Groupe' => 'INFO201',
            'formateur_Matricule' => '11533',
            'Id_module' => 'AG_INFO_TS_EGTS203',
            'code_seance' => '2S1',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL2',
            'Code_Groupe' => 'DEVOWFS204',
            'formateur_Matricule' => '19360',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '2S1',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL3',
            'Code_Groupe' => 'DEVOWFS203',
            'formateur_Matricule' => '13556',
            'Id_module' => 'DIA_DEVOWFS_TS_EGTS202',
            'code_seance' => '2S1',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD1',
            'Code_Groupe' => 'DEVOWFS202',
            'formateur_Matricule' => '13566',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '2S2',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD3',
            'Code_Groupe' => 'DEVOWFS206',
            'formateur_Matricule' => '17544',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '2S2',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD5',
            'Code_Groupe' => 'IDOSR204',
            'formateur_Matricule' => '15035',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '2S2',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID1',
            'Code_Groupe' => 'IDOSR201',
            'formateur_Matricule' => '10854',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '2S2',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID3',
            'Code_Groupe' => 'IDOSR203',
            'formateur_Matricule' => '13552',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '2S2',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SINFO',
            'Code_Groupe' => 'INFO202',
            'formateur_Matricule' => '8438',
            'Id_module' => 'AG_INFO_TS_M201',
            'code_seance' => '2S2',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL1',
            'Code_Groupe' => 'INFO201',
            'formateur_Matricule' => '11533',
            'Id_module' => 'AG_INFO_TS_EGTS203',
            'code_seance' => '2S2',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL2',
            'Code_Groupe' => 'DEVOWFS204',
            'formateur_Matricule' => '19360',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '2S2',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL3',
            'Code_Groupe' => 'DEVOAM201',
            'formateur_Matricule' => '13556',
            'Id_module' => 'DIA_DEVOAM_TS_EGTS202',
            'code_seance' => '2S2',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'COURS5',
            'Code_Groupe' => 'DEVOWFS202',
            'formateur_Matricule' => '19540',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '2S3',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD1',
            'Code_Groupe' => 'DEVOWFS204',
            'formateur_Matricule' => '10777',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '2S3',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD3',
            'Code_Groupe' => 'DEVOWFS203',
            'formateur_Matricule' => '10657',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '2S3',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD4',
            'Code_Groupe' => 'DEVOWFS201',
            'formateur_Matricule' => '19443',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '2S3',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD5',
            'Code_Groupe' => 'IDOCC201',
            'formateur_Matricule' => '10750',
            'Id_module' => 'DIA_IDOCC_TS_M201',
            'code_seance' => '2S3',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID1',
            'Code_Groupe' => 'IDOCS201',
            'formateur_Matricule' => '13716',
            'Id_module' => 'DIA_IDOCS_TS_M201',
            'code_seance' => '2S3',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID2',
            'Code_Groupe' => 'IDOSR202',
            'formateur_Matricule' => '10855',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '2S3',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL2',
            'Code_Groupe' => 'DEVOWFS205',
            'formateur_Matricule' => '19478',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '2S3',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL3',
            'Code_Groupe' => 'IDOSR203',
            'formateur_Matricule' => '13053',
            'Id_module' => 'DIA_IDOSR_TS_EGTS202',
            'code_seance' => '2S3',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SN1',
            'Code_Groupe' => 'DEVOWFS206',
            'formateur_Matricule' => '19826',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '2S3',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'COURS5',
            'Code_Groupe' => 'DEVOWFS201',
            'formateur_Matricule' => '19443',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '2S4',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD1',
            'Code_Groupe' => 'DEVOWFS203',
            'formateur_Matricule' => '10777',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '2S4',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD3',
            'Code_Groupe' => 'DEVOAM201',
            'formateur_Matricule' => '10657',
            'Id_module' => 'DIA_DEVOAM_TS_M201',
            'code_seance' => '2S4',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD4',
            'Code_Groupe' => 'DEVOWFS202',
            'formateur_Matricule' => '19540',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '2S4',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD5',
            'Code_Groupe' => 'IDOCC201',
            'formateur_Matricule' => '10750',
            'Id_module' => 'DIA_IDOCC_TS_M201',
            'code_seance' => '2S4',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID1',
            'Code_Groupe' => 'IDOCS201',
            'formateur_Matricule' => '13716',
            'Id_module' => 'DIA_IDOCS_TS_M201',
            'code_seance' => '2S4',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID2',
            'Code_Groupe' => 'IDOSR202',
            'formateur_Matricule' => '10855',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '2S4',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL2',
            'Code_Groupe' => 'DEVOWFS205',
            'formateur_Matricule' => '19478',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '2S4',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL3',
            'Code_Groupe' => 'IDOSR204',
            'formateur_Matricule' => '13053',
            'Id_module' => 'DIA_IDOSR_TS_EGTS202',
            'code_seance' => '2S4',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SN1',
            'Code_Groupe' => 'DEVOWFS206',
            'formateur_Matricule' => '19826',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '2S4',
            'Date' => '05/09/2023',
            'Jour_de_semaine' => 'MARDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'COURS5',
            'Code_Groupe' => 'DEVOWFS201',
            'formateur_Matricule' => '19443',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '3S1',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD1',
            'Code_Groupe' => 'DEVOWFS204',
            'formateur_Matricule' => '10777',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '3S1',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD3',
            'Code_Groupe' => 'DEVOWFS203',
            'formateur_Matricule' => '10657',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '3S1',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD4',
            'Code_Groupe' => 'DEVOWFS202',
            'formateur_Matricule' => '19540',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '3S1',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD5',
            'Code_Groupe' => 'IDOCC201',
            'formateur_Matricule' => '10750',
            'Id_module' => 'DIA_IDOCC_TS_M201',
            'code_seance' => '3S1',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID1',
            'Code_Groupe' => 'IDOCS201',
            'formateur_Matricule' => '13716',
            'Id_module' => 'DIA_IDOCS_TS_M201',
            'code_seance' => '3S1',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID2',
            'Code_Groupe' => 'IDOSR202',
            'formateur_Matricule' => '10855',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '3S1',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL2',
            'Code_Groupe' => 'DEVOWFS205',
            'formateur_Matricule' => '19478',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '3S1',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL3',
            'Code_Groupe' => 'IDOSR201',
            'formateur_Matricule' => '13053',
            'Id_module' => 'DIA_IDOSR_TS_EGTS202',
            'code_seance' => '3S1',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SN1',
            'Code_Groupe' => 'DEVOWFS206',
            'formateur_Matricule' => '19826',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '3S1',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'COURS5',
            'Code_Groupe' => 'DEVOWFS202',
            'formateur_Matricule' => '19540',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '3S2',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD1',
            'Code_Groupe' => 'DEVOWFS203',
            'formateur_Matricule' => '10777',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '3S2',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD3',
            'Code_Groupe' => 'DEVOAM201',
            'formateur_Matricule' => '10657',
            'Id_module' => 'DIA_DEVOAM_TS_M201',
            'code_seance' => '3S2',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD4',
            'Code_Groupe' => 'DEVOWFS201',
            'formateur_Matricule' => '19443',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '3S2',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD5',
            'Code_Groupe' => 'IDOCC201',
            'formateur_Matricule' => '10750',
            'Id_module' => 'DIA_IDOCC_TS_M201',
            'code_seance' => '3S2',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID1',
            'Code_Groupe' => 'IDOCS201',
            'formateur_Matricule' => '13716',
            'Id_module' => 'DIA_IDOCS_TS_M201',
            'code_seance' => '3S2',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID2',
            'Code_Groupe' => 'IDOSR202',
            'formateur_Matricule' => '10855',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '3S2',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL2',
            'Code_Groupe' => 'DEVOWFS205',
            'formateur_Matricule' => '19478',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '3S2',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL3',
            'Code_Groupe' => 'IDOSR204',
            'formateur_Matricule' => '13053',
            'Id_module' => 'DIA_IDOSR_TS_EGTS202',
            'code_seance' => '3S2',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SN1',
            'Code_Groupe' => 'DEVOWFS206',
            'formateur_Matricule' => '19826',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '3S2',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD1',
            'Code_Groupe' => 'DEVOWFS201',
            'formateur_Matricule' => '13566',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '3S3',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD3',
            'Code_Groupe' => 'DEVOWFS205',
            'formateur_Matricule' => '17544',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '3S3',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD5',
            'Code_Groupe' => 'IDOSR204',
            'formateur_Matricule' => '15035',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '3S3',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID1',
            'Code_Groupe' => 'IDOSR201',
            'formateur_Matricule' => '10854',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '3S3',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID3',
            'Code_Groupe' => 'IDOSR203',
            'formateur_Matricule' => '13552',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '3S3',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SINFO',
            'Code_Groupe' => 'INFO201',
            'formateur_Matricule' => '8438',
            'Id_module' => 'AG_INFO_TS_M201',
            'code_seance' => '3S3',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL1',
            'Code_Groupe' => 'INFO202',
            'formateur_Matricule' => '11533',
            'Id_module' => 'AG_INFO_TS_EGTS203',
            'code_seance' => '3S3',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL2',
            'Code_Groupe' => 'DEVOWFS204',
            'formateur_Matricule' => '19360',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '3S3',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL3',
            'Code_Groupe' => 'DEVOAM201',
            'formateur_Matricule' => '13556',
            'Id_module' => 'DIA_DEVOAM_TS_EGTS202',
            'code_seance' => '3S3',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD1',
            'Code_Groupe' => 'DEVOWFS202',
            'formateur_Matricule' => '13566',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '3S4',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD3',
            'Code_Groupe' => 'DEVOWFS206',
            'formateur_Matricule' => '17544',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '3S4',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD5',
            'Code_Groupe' => 'IDOSR204',
            'formateur_Matricule' => '15035',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '3S4',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID1',
            'Code_Groupe' => 'IDOSR201',
            'formateur_Matricule' => '10854',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '3S4',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID3',
            'Code_Groupe' => 'IDOSR203',
            'formateur_Matricule' => '13552',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '3S4',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SINFO',
            'Code_Groupe' => 'INFO201',
            'formateur_Matricule' => '8438',
            'Id_module' => 'AG_INFO_TS_M201',
            'code_seance' => '3S4',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL1',
            'Code_Groupe' => 'INFO202',
            'formateur_Matricule' => '11533',
            'Id_module' => 'AG_INFO_TS_EGTS203',
            'code_seance' => '3S4',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL2',
            'Code_Groupe' => 'DEVOWFS204',
            'formateur_Matricule' => '19360',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '3S4',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL3',
            'Code_Groupe' => 'DEVOWFS203',
            'formateur_Matricule' => '13556',
            'Id_module' => 'DIA_DEVOWFS_TS_EGTS202',
            'code_seance' => '3S4',
            'Date' => '06/09/2023',
            'Jour_de_semaine' => 'MERCREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'COURS5',
            'Code_Groupe' => 'DEVOWFS203',
            'formateur_Matricule' => '13556',
            'Id_module' => 'DIA_DEVOWFS_TS_EGTS202',
            'code_seance' => '4S1',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD1',
            'Code_Groupe' => 'DEVOWFS201',
            'formateur_Matricule' => '13566',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '4S1',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD3',
            'Code_Groupe' => 'DEVOWFS205',
            'formateur_Matricule' => '17544',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '4S1',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD5',
            'Code_Groupe' => 'IDOSR204',
            'formateur_Matricule' => '15035',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '4S1',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID1',
            'Code_Groupe' => 'IDOSR201',
            'formateur_Matricule' => '10854',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '4S1',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID3',
            'Code_Groupe' => 'IDOSR203',
            'formateur_Matricule' => '13552',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '4S1',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SINFO',
            'Code_Groupe' => 'INFO202',
            'formateur_Matricule' => '8438',
            'Id_module' => 'AG_INFO_TS_M201',
            'code_seance' => '4S1',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL2',
            'Code_Groupe' => 'DEVOWFS204',
            'formateur_Matricule' => '19360',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '4S1',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL3',
            'Code_Groupe' => 'IDOSR202',
            'formateur_Matricule' => '13053',
            'Id_module' => 'DIA_IDOSR_TS_EGTS202',
            'code_seance' => '4S1',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'COURS5',
            'Code_Groupe' => 'DEVOAM201',
            'formateur_Matricule' => '13556',
            'Id_module' => 'DIA_DEVOAM_TS_EGTS202',
            'code_seance' => '4S2',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD1',
            'Code_Groupe' => 'DEVOWFS202',
            'formateur_Matricule' => '13566',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '4S2',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD3',
            'Code_Groupe' => 'DEVOWFS206',
            'formateur_Matricule' => '17544',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '4S2',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD5',
            'Code_Groupe' => 'IDOSR204',
            'formateur_Matricule' => '15035',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '4S2',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID1',
            'Code_Groupe' => 'IDOSR201',
            'formateur_Matricule' => '10854',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '4S2',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID3',
            'Code_Groupe' => 'IDOSR203',
            'formateur_Matricule' => '13552',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '4S2',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SINFO',
            'Code_Groupe' => 'INFO202',
            'formateur_Matricule' => '8438',
            'Id_module' => 'AG_INFO_TS_M201',
            'code_seance' => '4S2',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL2',
            'Code_Groupe' => 'DEVOWFS204',
            'formateur_Matricule' => '19360',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '4S2',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL3',
            'Code_Groupe' => 'IDOSR202',
            'formateur_Matricule' => '13053',
            'Id_module' => 'DIA_IDOSR_TS_EGTS202',
            'code_seance' => '4S2',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'A DISTANCE',
            'Code_Groupe' => 'DEVOWFS201',
            'formateur_Matricule' => '19443',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '4S3',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'A DISTANCE',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD1',
            'Code_Groupe' => 'DEVOWFS203',
            'formateur_Matricule' => '10777',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '4S3',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD3',
            'Code_Groupe' => 'DEVOAM201',
            'formateur_Matricule' => '10657',
            'Id_module' => 'DIA_DEVOAM_TS_M201',
            'code_seance' => '4S3',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD4',
            'Code_Groupe' => 'DEVOWFS202',
            'formateur_Matricule' => '19540',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '4S3',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD5',
            'Code_Groupe' => 'IDOCC201',
            'formateur_Matricule' => '10750',
            'Id_module' => 'DIA_IDOCC_TS_M201',
            'code_seance' => '4S3',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID1',
            'Code_Groupe' => 'IDOCS201',
            'formateur_Matricule' => '13716',
            'Id_module' => 'DIA_IDOCS_TS_M201',
            'code_seance' => '4S3',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID2',
            'Code_Groupe' => 'IDOSR202',
            'formateur_Matricule' => '10855',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '4S3',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL2',
            'Code_Groupe' => 'DEVOWFS205',
            'formateur_Matricule' => '19478',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '4S3',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SN1',
            'Code_Groupe' => 'DEVOWFS206',
            'formateur_Matricule' => '19826',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '4S3',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'A DISTANCE',
            'Code_Groupe' => 'DEVOWFS201',
            'formateur_Matricule' => '19443',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '4S4',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'A DISTANCE',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD1',
            'Code_Groupe' => 'DEVOWFS204',
            'formateur_Matricule' => '10777',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '4S4',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD3',
            'Code_Groupe' => 'DEVOWFS203',
            'formateur_Matricule' => '10657',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '4S4',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD4',
            'Code_Groupe' => 'DEVOWFS202',
            'formateur_Matricule' => '19540',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '4S4',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD5',
            'Code_Groupe' => 'IDOCC201',
            'formateur_Matricule' => '10750',
            'Id_module' => 'DIA_IDOCC_TS_M201',
            'code_seance' => '4S4',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID1',
            'Code_Groupe' => 'IDOCS201',
            'formateur_Matricule' => '13716',
            'Id_module' => 'DIA_IDOCS_TS_M201',
            'code_seance' => '4S4',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID2',
            'Code_Groupe' => 'IDOSR202',
            'formateur_Matricule' => '10855',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '4S4',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL2',
            'Code_Groupe' => 'DEVOWFS205',
            'formateur_Matricule' => '19478',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '4S4',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SN1',
            'Code_Groupe' => 'DEVOWFS206',
            'formateur_Matricule' => '19826',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '4S4',
            'Date' => '07/09/2023',
            'Jour_de_semaine' => 'JEUDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'A DISTANCE',
            'Code_Groupe' => 'DEVOWFS202',
            'formateur_Matricule' => '19540',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '5S1',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'A DISTANCE',
        ]);
        Seance::create([
            'Id_Salle' => 'A DISTANCE',
            'Code_Groupe' => 'DEVOWFS206',
            'formateur_Matricule' => '19826',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '5S1',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'A DISTANCE',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD1',
            'Code_Groupe' => 'DEVOWFS204',
            'formateur_Matricule' => '10777',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '5S1',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD3',
            'Code_Groupe' => 'DEVOWFS203',
            'formateur_Matricule' => '10657',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '5S1',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD5',
            'Code_Groupe' => 'IDOCC201',
            'formateur_Matricule' => '10750',
            'Id_module' => 'DIA_IDOCC_TS_M201',
            'code_seance' => '5S1',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL2',
            'Code_Groupe' => 'DEVOWFS205',
            'formateur_Matricule' => '19478',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '5S1',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL3',
            'Code_Groupe' => 'IDOSR201',
            'formateur_Matricule' => '13053',
            'Id_module' => 'DIA_IDOSR_TS_EGTS202',
            'code_seance' => '5S1',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '8:30',
            'Horaire_fin' => '11:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'A DISTANCE',
            'Code_Groupe' => 'DEVOWFS202',
            'formateur_Matricule' => '19540',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '5S2',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'A DISTANCE',
        ]);
        Seance::create([
            'Id_Salle' => 'A DISTANCE',
            'Code_Groupe' => 'DEVOWFS206',
            'formateur_Matricule' => '19826',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '5S2',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'A DISTANCE',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD1',
            'Code_Groupe' => 'DEVOWFS203',
            'formateur_Matricule' => '10777',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '5S2',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD3',
            'Code_Groupe' => 'DEVOAM201',
            'formateur_Matricule' => '10657',
            'Id_module' => 'DIA_DEVOAM_TS_M201',
            'code_seance' => '5S2',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD5',
            'Code_Groupe' => 'IDOCC201',
            'formateur_Matricule' => '10750',
            'Id_module' => 'DIA_IDOCC_TS_M201',
            'code_seance' => '5S2',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL2',
            'Code_Groupe' => 'DEVOWFS205',
            'formateur_Matricule' => '19478',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '5S2',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SL3',
            'Code_Groupe' => 'IDOSR203',
            'formateur_Matricule' => '13053',
            'Id_module' => 'DIA_IDOSR_TS_EGTS202',
            'code_seance' => '5S2',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '11:00',
            'Horaire_fin' => '13:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'A DISTANCE',
            'Code_Groupe' => 'DEVOAM201',
            'formateur_Matricule' => '13556',
            'Id_module' => 'DIA_DEVOAM_TS_EGTS202',
            'code_seance' => '5S3',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'A DISTANCE',
        ]);
        Seance::create([
            'Id_Salle' => 'A DISTANCE',
            'Code_Groupe' => 'DEVOWFS203',
            'formateur_Matricule' => '13556',
            'Id_module' => 'DIA_DEVOWFS_TS_EGTS202',
            'code_seance' => '5S3',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'A DISTANCE',
        ]);
        Seance::create([
            'Id_Salle' => 'A DISTANCE',
            'Code_Groupe' => 'DEVOWFS204',
            'formateur_Matricule' => '19360',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '5S3',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'A DISTANCE',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD1',
            'Code_Groupe' => 'DEVOWFS201',
            'formateur_Matricule' => '13566',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '5S3',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD3',
            'Code_Groupe' => 'DEVOWFS205',
            'formateur_Matricule' => '17544',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '5S3',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD5',
            'Code_Groupe' => 'IDOSR204',
            'formateur_Matricule' => '15035',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '5S3',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID1',
            'Code_Groupe' => 'IDOSR201',
            'formateur_Matricule' => '10854',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '5S3',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID3',
            'Code_Groupe' => 'IDOSR203',
            'formateur_Matricule' => '13552',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '5S3',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SINFO',
            'Code_Groupe' => 'INFO201',
            'formateur_Matricule' => '8438',
            'Id_module' => 'AG_INFO_TS_M201',
            'code_seance' => '5S3',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '13:30',
            'Horaire_fin' => '16:00',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'A DISTANCE',
            'Code_Groupe' => 'DEVOAM201',
            'formateur_Matricule' => '13556',
            'Id_module' => 'DIA_DEVOAM_TS_EGTS202',
            'code_seance' => '5S4',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'A DISTANCE',
        ]);
        Seance::create([
            'Id_Salle' => 'A DISTANCE',
            'Code_Groupe' => 'DEVOWFS203',
            'formateur_Matricule' => '13556',
            'Id_module' => 'DIA_DEVOWFS_TS_EGTS202',
            'code_seance' => '5S4',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'A DISTANCE',
        ]);
        Seance::create([
            'Id_Salle' => 'A DISTANCE',
            'Code_Groupe' => 'DEVOWFS204',
            'formateur_Matricule' => '19360',
            'Id_module' => 'DIA_DEVOWFS_TS_M203',
            'code_seance' => '5S4',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'A DISTANCE',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD1',
            'Code_Groupe' => 'DEVOWFS202',
            'formateur_Matricule' => '13566',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '5S4',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD3',
            'Code_Groupe' => 'DEVOWFS206',
            'formateur_Matricule' => '17544',
            'Id_module' => 'DIA_DEVOWFS_TS_M201',
            'code_seance' => '5S4',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SDD5',
            'Code_Groupe' => 'IDOSR204',
            'formateur_Matricule' => '15035',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '5S4',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID1',
            'Code_Groupe' => 'IDOSR201',
            'formateur_Matricule' => '10854',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '5S4',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SID3',
            'Code_Groupe' => 'IDOSR203',
            'formateur_Matricule' => '13552',
            'Id_module' => 'DIA_IDOSR_TS_M201',
            'code_seance' => '5S4',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
        Seance::create([
            'Id_Salle' => 'SINFO',
            'Code_Groupe' => 'INFO201',
            'formateur_Matricule' => '8438',
            'Id_module' => 'AG_INFO_TS_M201',
            'code_seance' => '5S4',
            'Date' => '08/09/2023',
            'Jour_de_semaine' => 'VENDREDI',
            'No_Semaine_Calendrier' => 36,
            'No_Semaine_DRIF' => 1,
            'MH' => 2.5,
            'Horaire_debut' => '16:00',
            'Horaire_fin' => '18:30',
            'Type_seance' => 'PRESENTIEL',
        ]);
    }
}
